language: objective-c
before_install:
    - gem install cocoapods -v '0.32.1'
before_script:
    - export LANG=en_US.UTF-8
script: xcodebuild -workspace TravisCIPractice.xcworkspace -scheme TravisCIPractice -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO